name: Deploy website

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.80.0'
          extended: true

      - name: Build
        run: ./build.sh

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: website
          path: public

  deploy:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - name: Setup SSH keys and known_hosts
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-keyscan docs.chruemeli.io >> ~/.ssh/known_hosts
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
      
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: website
          path: website

      - name: Upload artifacts
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: scp -r website/* ${{ secrets.SSH_USER }}@/home/${{ secrets.SSH_USER }}/www/chruemeli-docs/
